name: flutter_multi_tool_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  url_launcher: ^6.2.6
  audioplayers: ^6.5.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/toolbox.png
    - assets/images/young.png
    - assets/images/adult.png
    - assets/images/elderly.png
    - assets/images/wordpress_logo.png
    - assets/icons/app_icon.png
